### ISSUE TITLE
Order Fraud Exception

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [conekta/conekta-php#129]
Hi, 
Wich class of the next Exceptions Handler give the "suspicious_behaviour" and how can i capture it?

- \Conekta\ProcessingError
- \Conekta\ParameterValidationError

Regards.

**Comment by eduardoconekta** [comment]
i think this could be `ProcessingError` because the error handler uses the API  response code
`conekta.errors.processing.charge.card_payment.suspicious_behaviour`
BTW you can also use `Handler` to manage general errors if `ProcessingError` does not work for what you want.
please look at https://developers.conekta.com/api?language=php#errors, you can put a condition for 
```
if   echo($error->getCode()) == 'conekta.errors.processing.charge.card_payment.suspicious_behaviour'
```
